# Generated by Django 3.2.15 on 2022-12-12 15:20

import core.fields
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models

from core.utils import insert_role_right_for_system


def add_rights(apps, schema_editor):
    insert_role_right_for_system(64, 153001)  # calculation
    insert_role_right_for_system(64, 153003)  # calculation update


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# calculation.migrations.0003_add_calculation_roles_for_admin

class Migration(migrations.Migration):

    replaces = [('calculation', '0001_initial'), ('calculation', '0002_auto_20210118_1426'), ('calculation', '0003_add_calculation_roles_for_admin'), ('calculation', '0004_clean_calc_tables')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRules',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', core.fields.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(db_column='ReplacementUUID', null=True)),
                ('calculation_class_name', models.CharField(blank=True, db_column='CalculationsClassName', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculationrules_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculationrules_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblCalculationRules',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CalculationRulesDetails',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('main', models.BooleanField(blank=True, db_column='Main', null=True)),
                ('params', models.JSONField(blank=True, db_column='Params', null=True)),
                ('class_params', models.JSONField(blank=True, db_column='ClassParams', null=True)),
                ('calculation_rules', models.ForeignKey(db_column='CalculationRulesUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='calculation.calculationrules')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculationrulesdetails_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculationrulesdetails_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblCalculationRulesDetails',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCalculationRules',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', core.fields.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(db_column='ReplacementUUID', null=True)),
                ('calculation_class_name', models.CharField(blank=True, db_column='CalculationsClassName', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calculation rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCalculationRulesDetails',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('main', models.BooleanField(blank=True, db_column='Main', null=True)),
                ('params', models.JSONField(blank=True, db_column='Params', null=True)),
                ('class_params', models.JSONField(blank=True, db_column='ClassParams', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calculation_rules', models.ForeignKey(blank=True, db_column='CalculationRulesUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='calculation.calculationrules')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calculation rules details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(
            code=add_rights,
        ),
        migrations.RemoveField(
            model_name='calculationrulesdetails',
            name='calculation_rules',
        ),
        migrations.RemoveField(
            model_name='calculationrulesdetails',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='calculationrulesdetails',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrules',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrules',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrules',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrulesdetails',
            name='calculation_rules',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrulesdetails',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrulesdetails',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='historicalcalculationrulesdetails',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='CalculationRules',
        ),
        migrations.DeleteModel(
            name='CalculationRulesDetails',
        ),
        migrations.DeleteModel(
            name='HistoricalCalculationRules',
        ),
        migrations.DeleteModel(
            name='HistoricalCalculationRulesDetails',
        ),
    ]
